### ISSUE TITLE
Word count and character count (including spaces and line breaks) statistics

### ISSUE THREAD

**Issue by Arvigell** [micz/ThunderStats#106]
Dear Developer, I am happy with your addon and I thank you for the effort you put into it. Please consider the following improvement:

Please add the word/character count statistics that:
- will show the exact number of words/characters send to a given recipient in a given period of time excluding the e-mail signature text, the quoted text (in the middle of the message) and the thread history messages (usually included in the e-mail below the e-mail signature).

- as the above but for the words/characters received in e-mails from a given sender

Why would it be useful? Being a project manager I could easily calculate the time spent on e-mail communication by multiplying the words/characters typed in (while sending e-mails) by my average typing speed and also by multiplying the words/characters read (received from a sender) by my average reading speed. This feature would greatly enhance measuring any e-mail communication effort.

Please let me know if this would be possible. If however you have a better proposal on how to approach the e-mail communication effort measuring, please share your thoughts.

Thank you very much!

**Comment by micz** [comment]
Dear Arvigell,

thank you for your idea!
Sadly there is no way in Thunderbird to always correctly check which part of a message is a reply and which part is not.

The only way to achive this is described in issue #108, but it could save information only from the first activation.
It will be an huge implementation, but I'l list it here to keep track of it for a future release.

I'm going to close this issue.

**Comment by Arvigell** [comment]
Thank you for your reply!
