### ISSUE TITLE
Add a statusbar icon

### ISSUE THREAD

**Issue by micz** [micz/ThunderStats#112]
Add a status bar icon, with this behavior:
- When clicked it opens (or switches to) the thunderstat tab.
- Has a tooltip that shows the today sent / received messages.
- Is activable using an option.
- Has an option to choose the time interval for the tooltip updates.
- When updating the icon changes (this behavior activable with another option).

**Comment by CodingSpiderFox** [comment]
I would like to be able to choose some tiny metrics to be displayed directly in the status bar. Like for example: avg messages per day, avg response time etc.

**Comment by micz** [comment]
I know it has been many years of silence, but finally work on ThunderStats has resumed, as described [here](https://github.com/micz/ThunderStats/issues/195).

Statusbar icons are no longer available to addons at the moment; therefore, I’m closing this issue.
