### ISSUE TITLE
Counting Very Few Emails

### ISSUE THREAD

**Issue by jfox1980** [micz/ThunderStats#120]
I have an inbox with 55 emails, 5 of which are yesterday.

In ThunderStats for yesterday, 0 emails are found. If I go to the Sent folder, I know that I have 126 items for today. ThunderStats shows 3 sent mails and 14 received.

All of my other folders act in a similar fashion.

**Comment by micz** [comment]
ThunderStats uses the Thunderbird database, so, to show the stats its needed that the Global Indexing is active and that the folders you want to do the stats on are not excluded by the Global Indexing.
Given that, ThunderStats can only count mail where a given account address is in the to: or cc: field for received mails.
If you receive mails from a mailing list, you need to add that address in the Custom Identities:

![164710](https://cloud.githubusercontent.com/assets/61795/11048987/5239ea1c-873b-11e5-959b-0bbcccfb72ad.png)

May you check also if the "Last Index Update" and "Last Indexed Message", in the top right corner of the ThunderStats tab are updated?

**Comment by jfox1980** [comment]
In Options --> Options --> Advanced, 'Enable Global Search and Indexer' is
enabled.

When I click on ThunderStats, I show the following: Last index update:
11/10/2015 10:19:45 AM.

I also notice that all of my folders aren't listed in Inbox Zero Status. It
shows Inbox (42) and Facebook (2) but there are several more folders under
my Inbox that have a lot more mail.

For example, I have an 'Old Trash' folder, and under that are folders for
several previous months of trash. I checked the headers and the bulk appear
to be "To: Me <techsupport@edcpub.com>" (which is my address). There are
thousands of emails in each of these folders that are unaccounted for.

**Comment by micz** [comment]
The Inbox Zero Status shows only the folders where today mails have been moved.
On the yesterday tab it shows the same graph for the yesterday emails.
A folder statistics is under development, see #75.

May you do a custom query on one day (today or yesterday) one with the "business only" option enabled and one with that option disabled and tell me if the results of sent and received mails are the same and if they are equals to the once shown in the today and yesterday tab?
Thanks.

**Comment by micz** [comment]
After 15 day I close this issue.
Feel free to comment or open it again if you need more support.
