### ISSUE TITLE
Local folders not included as an account or in ALL account statistics.

### ISSUE THREAD

**Issue by MadMattAu** [micz/ThunderStats#122]
Just tried out this stats package and it looked very promising,  until I worked out that my mail stored in local folders is not included.  SO I received no mail on the acounts because the accounts have no inbox, except the global inbox.

**Comment by micz** [comment]
May you tell me which version of Thunderbird, which version of the addon and which operative system?

May you also activate the "Show identities in the account selector" option in the preference panel, then close and reopen the ThunderStats tab and check in the "Choose Account" dropdown list if the mail addresses are visibile under an account?
There are accounts visible in the "Choose Account" dropdown list other than the "other identities" one?

**Comment by micz** [comment]
I'm trying to replicate what it's happening to your installation.
I set up a new profile with a new account that uses the Global Inbox.
I correctly get new email in the Today "Mails" widget on the left and also in the Top Recipients and Top Senders.
What I'm not correctly getting is the "Inbox Zero Status" widget. To fix this I deselected the "Search for mails in the Inbox folders only in the folders for the selected account" option.

May you try to change that option?
Thank you.

**Comment by MadMattAu** [comment]
On 12/01/2016 6:36 AM, Mic wrote:
>
> I'm trying to replicate what it's happening to your installation.
> I set up a new profile with a new account that uses the Global Inbox.
> I correctly get new email in the Today "Mails" widget on the left and 
> also in the Top Recipients and Top Senders.
> What I'm not correctly getting is the "Inbox Zero Status" widget. To 
> fix this I deselected the "Search for mails in the Inbox folders only 
> in the folders for the selected account" option.
>
> May you try to change that option?
> Thank you.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/micz/ThunderStats/issues/122#issuecomment-170673991>.
>


I now appear to be able to get the mails for today.  If there are few 
enough.  The past 7 days figures just wave that blue thing forever.  
Would rebuilding the global inbox help,  or are the stats drawn directly 
from MBOX or MSF files?  In my case around 15Gb



-- 
“Against stupidity the gods themselves contend in vain.” /― Friedrich 
von Schiller, Die Jungfrau von Orleans /

**Comment by micz** [comment]
Rebuilding the global index could help. All the data are read from the Thunderbird global index, except for some information in the "Inbox Zero Status" widget.
May you send me at m@micz.it a screenshot for the "The past 7 days figures just wave that blue thing forever." if it remains after the rebuilding?

I close the issue, feel free to reopen it if needed.
Thank you.
