### ISSUE TITLE
SQLite Manager Alert

### ISSUE THREAD

**Issue by rms-cjohns** [micz/ThunderStats#130]
Receiving the attached alert, and statistics do not show up.  After clicking OK in the message box, Thunderbird opens and shows all the accounts and emails.  Email continues to come in and go out, but statistics are showing 0.
![alert](https://cloud.githubusercontent.com/assets/16802111/17219793/4a8772fe-54b2-11e6-9d89-cbd78387bfae.png)

**Comment by micz** [comment]
The message means that the addon is not able to open the Thunderbird database to query the statistics from it.
When you open Thunderbird the ThunderStats tab is already open? May you try to close and reopen Thunderbird without the ThuderStats tab opened and then open the ThunderStats tab? Do you still get the message? If yes, when?
Which version of ThunderBird are you using? On which Operating System?

**Comment by rms-cjohns** [comment]
The user does not see the error message until he clicks on thunderstats.

This is on Thunderbird 38.2.0, on Windows 7

Thanks,
Chris Johns
Network Administrator
Recovery Management Services, Inc.
Phone: 630-657-1350
Email: cjohns@rmscollects.com<mailto:cjohns@rmscollects.com>



CONFIDENTIALITY NOTICE
This email message, including all attachments, is for the sole use of the intended recipients and may contain confidential and privileged information.  If you are not the intended recipient, you may NOT use, disclose, copy or disseminate this information.  Please contact the sender by reply email and immediately destroy all copies of the original message including all attachments.  Even if you are the intended recipient of this email, the author requests that you not forward it to any other person without prior consent.

**Comment by micz** [comment]
That error means that ThunderStats was not able to access the Thunderbird index database. It should never happen.

If you feel confident, you could try to force Thunderbird to rebuild the index, as described here: https://support.mozilla.org/en-US/kb/rebuilding-global-database

**Comment by micz** [comment]
Closed after 2 months.
