### ISSUE TITLE
How long should it take to process +250K emails

### ISSUE THREAD

**Issue by plaidpants** [micz/ThunderStats#143]
I have +250K emails (9.1GB) in thunderbird, I can see the today stats right away but anything else just shows the animated progress icon. I let it run overnight but nothing appeared. Is this too much for it to process in a reasonable time?

**Comment by micz** [comment]
The needed time depends also on your PC performance.
I also have more than 9GB of emails, nut ThunderStats takes less than a minute to give a result.
If you want more help, please send me the debugger report (form the info tab), so I can check if there is any problem.
