### ISSUE TITLE
Date selection in "Custom View" is not displayed correctly

### ISSUE THREAD

**Issue by nyaff** [micz/ThunderStats#144]
Date selection in "Custom View" is not displayed correctly on my system.

Today is 7 March 2017. When I select the two day period 6 March 2017 to 7 March 2017 these dates are displayed as "06 Oct  03 2017" and "07 Oct  03 2017" (in both cases the "7" of "2017" is hidden).

![Screenshot showing the problem](http://i.imgur.com/6eBAZu0.png)

If I select 1 January 2017 and 28 February 2017 these dates are displayed as "01 Oct  01 2017" and "28 Oct  02 2017"

**Comment by micz** [comment]
May you send me a debugger report, from the "Info" tab?
Thank you

**Comment by nyaff** [comment]
I've sent you a debugger report.

**Comment by micz** [comment]
I can't find it. May you send it again? May you also add a reference to this issue in the debugger message?
After you click the "send report" button, it opens a mail message with the debugger report in it, you need to actually send that email, it's not done automatically.
Thanks.

**Comment by micz** [comment]
Nevermind, it was caught by the antispam filter. I'll check it soon.

**Comment by nyaff** [comment]
It looks like ThunderStats cannot handle the Short Date Format used on my system:
ddd dd MMM yy

When I changed the Short Date Format to dd/MM/yy ThunderStats showed today's date as
02/ 04/    2017

**Comment by micz** [comment]
I know it has been many years of silence, but finally work on ThunderStats has resumed, as described [here](https://github.com/micz/ThunderStats/issues/195).

The addon is being rewritten from scratch; therefore, I’m closing this issue.
