### ISSUE TITLE
Deleting email decrements "Received" count

### ISSUE THREAD

**Issue by justin-c-rounds** [micz/ThunderStats#146]
Great idea for an add-on! However, when I delete an email the "received" count decrements by one. For example, if the Yesterday tab indicates I received 18 emails, then I delete an email from yesterday and click the "update" button, the yesterday tab will read 17.

I would expect the "received" stats to actually indicate the number of emails received, not just the ones sitting in my inbox.

Thank you!

**Comment by micz** [comment]
When you delete an email, Thunderbird removes it also from its internal database, so the stats, that are counted "live", show one mail less.
If you archive an email or move it to a folder different from the inbox, the mail is counted in the stats.
