### ISSUE TITLE
ThunderStats TAB does not display anything & TAB wont Close

### ISSUE THREAD

**Issue by AppTester7** [micz/ThunderStats#150]
After opening up the new ThunderStats TAB in the main Email Window, there is literally nothing
displayed it the TAB at all.

Attempting to close the ThunderStats TAB does nothing when you click on 'Close Tab'.

User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0 SeaMonkey/2.51
Build identifier: 20170619085306

I used the following site to convert the .XPI add-on:
http://addonconverter.fotokraina.com/

Im using the 64-Bit version of SeaMonkey
Windows 8.1 Pro x64

**Comment by AppTester7** [comment]
Looks like a great add-on, hope i can use it in the near future!

**Comment by micz** [comment]
I'm sorry, this addon is tested only on Thunderbird. If you want to contribute on the Seamonkey compatibility, feel free to make a pull request. Thank you!
