### ISSUE TITLE
Stats for my employees

### ISSUE THREAD

**Issue by anavasis** [micz/ThunderStats#151]
i would like to use this add on in order to track my employees starts. The problem is that all are using the same 2 email addresses and can only be tracked or if we put a code or with the wise stamp signature they have in each email.
Please help.
Thanks

**Comment by anavasis** [comment]
I have no news is there no answer?
Thanks

**Comment by micz** [comment]
I'm sorry at the moment the only way to separate the stats is to use different emails.
