### ISSUE TITLE
top-xxx does not work with higher values / new function: creating a "distinct(email-id)" list for a given period

### ISSUE THREAD

**Issue by drfedtke** [micz/ThunderStats#153]
I wanted to analyze 2017 in my mail box to check with whom
I worked together for sending christmas cards.

for that I set the  top-xxx value xxx to 99, but when I create a
statistic for 2017 the top-xxx is empty.

maybe it would be cool to have a complete list, means that the
xxx value of "top-xxx" can be "infinite".

thanks. your tool is great.

**Comment by micz** [comment]
I tried it with 99 limit and it worked. for one year it takes a lot of minutes on a fast PC, so maybe you stopped it before it completes.
Thank you!
