### ISSUE TITLE
Thunderstats Not Giving Total of Emails Received

### ISSUE THREAD

**Issue by fairal** [micz/ThunderStats#156]
I am new to Thunderbird email and Thunderstats. I installed it so I could measure the amount of emails I receive and send throughout the week/month. The totals it shows me only reflects what is currently in my Inbox and Sent folders. As I delete emails the totals change. I need to be able to measure all emails received and sent regardless if I delete or move emails into another folder. Is that an option? Thank you!

**Comment by micz** [comment]
If you delete a message, Thunderbird removes it from its internal database, so ThunderStats can not show it.
With a custom database, like the one described in #9, I could keep count also of the deleted messages and show it in the stats with an option.
At the moment it's not possible, i'm sorry.
