### ISSUE TITLE
Only INBOXES are included. What about Archives?

### ISSUE THREAD

**Issue by unalignedcoder** [micz/ThunderStats#160]
I have a huge archive of emails spanning over more than a decade in my "Archives" folder within the "Local" folder. This seems to be ignored by ThunderStats. Is there any way to include this in the indexing?

**Comment by unalignedcoder** [comment]
...any chance someone is going to consider this, or explain to me why this isn't a feature I should expect? Indexing Local Folders...?

**Comment by unalignedcoder** [comment]
I seem to understand from this issue
https://github.com/micz/ThunderStats/issues/122
that Thunderstats does index the local folders?
Could anyone help me with this? My local folders are not being scanned.

**Comment by micz** [comment]
I know it has been many years of silence, but finally work on ThunderStats has resumed, as described [here](https://github.com/micz/ThunderStats/issues/195).

The addon is being rewritten from scratch with a completely different system for gathering data; therefore, I’m closing this issue.
