### ISSUE TITLE
compatibility with TB 60 / 62

### ISSUE THREAD

**Issue by n8v8R** [micz/ThunderStats#162]
Suppose there is awareness of the changes for add-ons towards TB 60 https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_57
And then then there will be further changes towards TB 62

Yet, ThunderStats seems not working with TB 60.0b9 (64-bit on Win 10).

Opening the Stats tab:

> Removing unsafe node. Element: select.  jquery-3.3.1.min.js:2:9943
> Security Error: Content at moz-nullprincipal:{87d63226-9933-4549-b271-bff7e9fa584c} may not load or link to chrome://thunderstats/content/mzts-statstab.xhtml.
> Removed unsafe URI from element attribute. Element: a. Attribute: href.  jquery-3.3.1.min.js:2:10422
> Removing unsafe node. Element: select.  jquery-3.3.1.min.js:2:10422
> Flattening unsafe node (descendants are preserved). Element: input.  jquery-3.3.1.min.js:2:22813
> Flattening unsafe node (descendants are preserved). Element: form. jquery-3.3.1.min.js:2:81983
> Removing unsafe node. Element: select.  jquery-3.3.1.min.js:2:38093
> TypeError: a is null[Learn More]  jquery-3.3.1.min.js:2:38149
> 	xe chrome://thunderstats/content/jslib/jquery-3.3.1.min.js:2:38149
> 	Re chrome://thunderstats/content/jslib/jquery-3.3.1.min.js:2:46878
> 	append chrome://thunderstats/content/jslib/jquery-3.3.1.min.js:2:48574
> 	loadIdentitiesSelector chrome://thunderstats/content/mzts-statstab.ui.js:35:3
> 	onLoad chrome://thunderstats/content/mzts-statstab.js:76:4
> nsMsgDBFolder::GetPrettiestName is deprecated and will be removed soon.

---
Opening the settings panel

> TypeError: Components.classes['@mozilla.org/xmlextras/xmlhttprequest;1'] is undefined[Learn More]  mzts-settings.js:87:7
> 	loadInfoFile chrome://thunderstats/content/mzts-settings.js:87:7
> 	onLoad chrome://thunderstats/content/mzts-settings.js:37:3
> 	onload chrome://thunderstats/content/mzts-settings.xul:1:1

**Comment by RealRaven2000** [comment]
> And then then there will be further changes towards TB 62
Yes at the moment legacy Add-ons do not run at all. If you are using XUL or XPCOM please join the discussion on Tb-Planning on how / what APIs *we* (Add-ons authors) need to create in order to replace this technology in Thunderbird. They still haven't decided on forking m-c so all changes in firefox from version 61 onwards are destructive without workaround.

**Comment by n8v8R** [comment]
I was under the impression that TB would follow suit FF with web extentions

**Comment by RealRaven2000** [comment]
> I was under the impression that TB would follow suit FF in the way of web extentions
this is exactly the reason why we need to write APIs in order to replace XPCOM. The exact replacement of XUL overlays hasn't even been designed / invented yet.

**Comment by micz** [comment]
Closed in https://github.com/micz/ThunderStats/commit/cd6f3c528fdd1014b8e3620e9f18483f57cf5571.
