### ISSUE TITLE
ThunderStats reports fewer received Emails (probably) due to missing Custom Identity that I cannot add

### ISSUE THREAD

**Issue by dwarf007** [micz/ThunderStats#164]
I received 48 Emails today, but thunderstats only reports 16. Same for all the other days. Always much fewer Emails then what I really received.
I receive numerous Emails on an Email address alias and this might be the cause, therefore I tried to add that address in the Custom Identities. Unfortunately, whenever I add something to Custom Identities and then close the dialog, it seems that the Email(s) is/are not saved.
Is this a bug?

Just another question regarding the custom identities: does this mean that any Email for which I am in bcc, will not be counted?

**Comment by micz** [comment]
You need to close and reopen the ThunderStats tab to see the Custom Identities work. If the additional email addresses are not saved, may you post the log from the error console (open with CRTL+SHIFT+J in Thunderbird).
Which Thunderbird version are you using?

Given how Thunderbird saves the info on received emails, there is no way to count also bbc-ed emails. This addons show stats using the internal Thunderbird database.

**Comment by dwarf007** [comment]
Thunderbird 60.3.0 (64-bit) on macOS Sierra (10.12.6)

Error console logs, are:
![image](https://user-images.githubusercontent.com/2540393/48311775-22bd5c80-e5a5-11e8-9e5e-6f0287986eb8.png)

**Comment by micz** [comment]
This addon was compatible only with the first 60.0 version. I've now updated the max Thunderbird version on the AMO website. On every new Thunderbird version there are changes in the core that breaks how the addons work.
For this reason I've discontinued all my addons. Too much hours are needed just to keep an addon working with new Thunderbird versions.
I'm sorry.

**Comment by dwarf007** [comment]
Oh.. that's sad.  :-( But thanks for the fast answers!

**Comment by micz** [comment]
@cleidigh is helping working on compatibility for future releases, so stay tuned. :-)
