### ISSUE TITLE
Fix current year in the italian translation

### ISSUE THREAD

**Issue by micz** [micz/ThunderStats#168]
Fix the current yesr in the italian translation;

https://github.com/micz/ThunderStats/blob/dfc0f18e4f10e390b783fda6af116aabd702acad/src/chrome/locale/it/mzts-statstab.dtd#L58

**Comment by cleidigh** [comment]
@micz 
It looks like "LastYear" is also wrong, I think the two are swapped?

**Comment by micz** [comment]
Yes, the two are swapped.
