### ISSUE TITLE
Inbox Zero Help Page Missing

### ISSUE THREAD

**Issue by daniel-barrows** [micz/ThunderStats#179]
The "What is Inbox Zero?" Pane of the "Info" tab of ThunderStats in the code at [mzts-statstab.xhtml#L373](https://github.com/micz/ThunderStats/blob/cd6f3c528fdd1014b8e3620e9f18483f57cf5571/src/chrome/content/mzts-statstab.xhtml#L373) links to https://micz.it/thunderdbird-addon-thunderstats-your-thunderbird-statistics/what-is-inbox-0/ which is currently a 404 page. The page is not in Google Cache or the Wayback Machine. The link could probably be changed to a relevant existing page to be found via a web search.

**Comment by micz** [comment]
Fixed. Thank you.
