### ISSUE TITLE
Email addresses should not be case-sensitive

### ISSUE THREAD

**Issue by daniel-barrows** [micz/ThunderStats#180]
I setup an email account using mixed case for the domain (eg. mail@Example.com). ThunderStats showed no mail for this account.

I added mail@example.com as a Custom Identity in the ["Custom Identities" tab](https://github.com/micz/ThunderStats/blob/dfc0f18e4f10e390b783fda6af116aabd702acad/src/chrome/content/mzts-settings.xul#L223) in the Settings Dialog, which fixed the problem.

I propose that ThunderStats downcase all account emails in order to normalize them. We could just downcase the domain, since [technically](https://stackoverflow.com/a/9808332) domains must be case insensitive and addresses may be case sensitive. However, most email servers are case insensitive anyhow and this is much more likely to be helpful to users than problematic.

**Comment by micz** [comment]
I know it has been many years of silence, but finally work on ThunderStats has resumed, as described [here](https://github.com/micz/ThunderStats/issues/195).

The addon is being rewritten from scratch with a completely different system for gathering data; therefore, I’m closing this issue.
