### ISSUE TITLE
Add support for statistics on Local Folders

### ISSUE THREAD

**Issue by unalignedcoder** [micz/ThunderStats#185]
Not really an issue, but... All my mail is archived in local folders, would be great to have some statistics about it.

**Comment by cleidigh** [comment]
@unalignedcoder 
@micz 
I am looking into this with the original author to get a better idea of the implications.
@cleidigh

**Comment by micz** [comment]
If the Local Folders are being indexed by Thunderbird, they are considered for the stats.
Have you excluded the Local Folder from the Global Indexing?

**Comment by unalignedcoder** [comment]
Local Folders don't appear in the list of accounts

**Comment by unalignedcoder** [comment]
Stats showing only one email sent in 2012. Notice the date range.
![2020-02-09 12_38_56-ThunderStats - Mozilla Thunderbird](https://user-images.githubusercontent.com/16850566/74097680-402afe80-4b39-11ea-9ce3-1a69e12320fa.png)

**Comment by unalignedcoder** [comment]
My actual Local Folder archives, showing a lot of content.

![2020_02_09_12_41_37_2012_Local_Folders_Mozilla_Thunderbird](https://user-images.githubusercontent.com/16850566/74097736-00184b80-4b3a-11ea-9b1e-0809711f2598.png)

**Comment by unalignedcoder** [comment]
I will also notice that, once asked ThunderStats for the complete date range as shown above, this little animation:
![2020-02-09 12_48_17-ThunderStats - Mozilla Thunderbird](https://user-images.githubusercontent.com/16850566/74097782-7a48d000-4b3a-11ea-992b-74bdabe10bda.png)
never stops. Something went wrong during the process?

**Comment by unalignedcoder** [comment]
I've deleted `global-messages-db.sqlite` a couple of times to allow rebuilding of the index, but I always get partial, minimal results.

**Comment by dabrain34** [comment]
IMAP folders are not taken into account, is it normal ?

**Comment by micz** [comment]
> My Local Folders are normally indexed by Thunderbird.
> 
> However: "Local Folders" doesn't appear in ThunderStats list of accounts.

"Local Folders" isn't an account, the mails are indexed under a normal identity (sender email address) by Thunderbird.

**Comment by micz** [comment]
> IMAP folders are not taken into account, is it normal ?

IMAP folders are taken into account if they are indexed by Thunderbird.

**Comment by micz** [comment]
> I've deleted `global-messages-db.sqlite` a couple of times to allow rebuilding of the index, but I always get partial, minimal results.

How big is your `global-messages-db.sqlite` file?

**Comment by micz** [comment]
I know it has been many years of silence, but finally work on ThunderStats has resumed, as described [here](https://github.com/micz/ThunderStats/issues/195).

The addon is being rewritten from scratch with a completely different system for gathering data; therefore, I’m closing this issue.
