### ISSUE TITLE
Use case - doesn't really work for summarizing email over a long time period

### ISSUE THREAD

**Issue by Olghn** [micz/ThunderStats#189]
I was happy to discover Thunderstat because up to now I have been making histograms manually using the 'Search' by date command to count the numbers of emails in my mail folders within each year.

The use case is that since the 1990's (or even 1980's?) I have switched between many computers and have accumulated a trail of debris. Machines within a machine. Data on backups etc.
Now that I am no longer working I have time to try and organise and recover email from all these sources and put it into Thunderbird. I use histograms to get an overview of what time periods I am likely missing data. Ideally I would like monthly granularity (to much of a hassle doing it manually).
My mail folders total about 8GB at present - and when I try and set Thunderstats to work on them all it never seems to complete.

OK - I understand there may not be much demand for this use case but I thought I should document it.

**Comment by micz** [comment]
I know it has been many years of silence, but finally work on ThunderStats has resumed, as described [here](https://github.com/micz/ThunderStats/issues/195).

The addon is being rewritten from scratch with a completely different system for gathering data; therefore, I’m closing this issue.
