### ISSUE TITLE
Compatibility with GMail?

### ISSUE THREAD

**Issue by jgerth** [micz/ThunderStats#190]
I have two accounts and ThunderStats does not show any statistics for my Google/GMail account. It works fine with the other one. Thank you for your support.

**Comment by micz** [comment]
I know it has been many years of silence, but finally work on ThunderStats has resumed, as described [here](https://github.com/micz/ThunderStats/issues/195).

The addon is being rewritten from scratch; therefore, I’m closing this issue.
The new version is working with Gmail, with some refinement needed, as described in #196.
