### ISSUE TITLE
Not possible to select an account

### ISSUE THREAD

**Issue by DO10-01** [micz/ThunderStats#191]
Tunderstats Version: 1.4.5
Thunderbird Version: 68.12.0 (64bit)

- In Tunderstats Tab is is not possible to select an account.
- In Tunderstats preferences is it not possible to

1. 1. select an start account
2. select an account on more identity tab

![image](https://user-images.githubusercontent.com/71927287/94339172-2e2e9b00-fff8-11ea-8272-36b067491e22.png)

![image](https://user-images.githubusercontent.com/71927287/94339188-43a3c500-fff8-11ea-9bd0-36b310022ef0.png)

Best regards!

**Comment by micz** [comment]
I know it has been many years of silence, but finally work on ThunderStats has resumed, as described [here](https://github.com/micz/ThunderStats/issues/195).

The addon is being rewritten from scratch; therefore, I’m closing this issue.
