### ISSUE TITLE
Compatibility with Thunderbird v78.*.*

### ISSUE THREAD

**Issue by rfwolff** [micz/ThunderStats#192]
I am wondering whether any update to support the latest versions of Thunderbird are planned. Thanks for your great work on this app which I enjoy a lot.

**Comment by cyrpaut** [comment]
The project seems not to have received updates for 2 years now. However I'd love to have a version of thunderstats for 78.*

**Comment by bkjproductions** [comment]
+1 for Thunderbird 78.*

**Comment by Iaktim** [comment]
I'd like to me too. I love ThunderStats. I'm using Thunderbird for ThunderStats.

**Comment by BenjaminKobjolke** [comment]
Yes please update this wonderful addon!

**Comment by bwandernoth** [comment]
I think we all love ThunderStats. But it prevented me from upgrading Thunderbird for quite some time. Just found this:
https://github.com/devmount/third-stats
I thought I share. Looks quite promising.

**Comment by micz** [comment]
I know it has been many years of silence, but finally work on ThunderStats has resumed, as described [here](https://github.com/micz/ThunderStats/issues/195).

I'm targeting Thunderbird 128+; therefore, I’m closing this issue.
