### ISSUE TITLE
Can´t install thunderstats normaly

### ISSUE THREAD

**Issue by JPRuehmann** [micz/ThunderStats#40]
Hello if Itry to install it only shows Downloading and nothing happens.
If I install in safe-mode it gets installed but if I than restart normaly and try to open the settings nothing happens and I only can disable the extension after open the main menu then push disable at the extension entry and quit thunderbird by clicking quit in the Main Menu. after then restarting thunderbird by hand it works normally again.

I´m using Thunderbird 31.0, Java 1.9, Kubuntu 14.04 (LTS)
my Language is de-ade

Thanks,
JPR

**Comment by JPRuehmann** [comment]
If I disable ade Language pack it works.
I will contact them to. But it would be fine if the Extension would work with every Language nut only US.
Thanks,
JPR

**Comment by micz** [comment]
Currently ThunderStats is available only in English, but I'll add multilanguage for the 1.0 release.
I've tested it with the "it" locale and it works, even if all the labels are in English.

The de-ade language pack you are referring to is this: https://addons.mozilla.org/it/firefox/addon/sprachpaket-ade/ ?

May you post here the error log you get with the language pack active?
Thanks.

**Comment by micz** [comment]
I was not able to install the addon I linked in my previous post, since it's not compatible with Thunderbird. Please, may you post here the link of the language pack are you using?
Thanks.

**Comment by JPRuehmann** [comment]
http://www.fehler-haft.de/thunderbird/ade-tb-31.0.c.xpi

**Comment by micz** [comment]
I installed the language pack and I had no problems.
I'm using Thunderbird 31.5 on lubuntu 14.10.

May you post the error console log? You can open it with crtl+shift+J or from the tools menu.

**Comment by JPRuehmann** [comment]
Thanks for your answer
After disabling de-ade, restart, enabling de-de, restart, disabling de-de, restart, enabling de-ade and restart it now works for me to.
Thanks,
JPR
