### ISSUE TITLE
'Last 7 days' graphs updating incorrectly

### ISSUE THREAD

**Issue by RollaTroll** [micz/ThunderStats#54]
When the 'update' button is pressed, or the focus is switched to that tab, it attempts to update the graphs. It then displays the next day ('tomorrow') int he first slot, then each consecutive update pulls all other dates forward to match (offsetting by 1 say forward by the end). Once it has changes all bars, one final update will reset it to the correct dates, and the cycle restarts.

**Comment by micz** [comment]
Please, try the version 0.2alpha7 here: https://www.dropbox.com/s/ufl7rhi5bpg0m9b/ThunderStats-0.2alpha7.xpi?dl=0
Is the bug resolved?

The full changelog for this version is here:
- Bug fixing.
- Minor improvements.
- New identities / accounts selector.
- Graphs improvements.
- Debug options added.

**Comment by micz** [comment]
Consider also that the version 0.2alpha7 has this bug: https://github.com/micz/ThunderStats/issues/52

**Comment by micz** [comment]
Fixed in version 0.2 released today.
