### ISSUE TITLE
Per folder statistics

### ISSUE THREAD

**Issue by micz** [micz/ThunderStats#75]
Implement a wrapper function that generates all statistics and gives back the results structure for either
a) any Folder
b) any Folder + its children
c) an account (including all folders)

So it could be possible to create code that eventually works with the folder pane to make per folder statistics.

~~Add also an interactive graphic that shows which folders take up the most space, with the possibility to do a drill down into the subfolders.~~ Moved to issue #124.

[props Axel Grude]

<br>

**UPDATE 2024/09/06**

To Do:
- [x] Add multiselect to choose folders
- [x] Add a checkbox to include subfolders of the selected folders
- [x] Pass the folders to the statscore (with the subfolders option)
- [x] If "All account" is choosen, disable folder filtering.

**Comment by l-g** [comment]
Is this implemented or still on the TODO-list?

**Comment by micz** [comment]
Development will be restarted in the new ThunderStats.
This feature will be released in version 2.2.

**Comment by micz** [comment]
To Do:
- [ ] Add multiselect to choose folders
- [ ] Add a checkbox to include subfolders of the selected folders
- [ ] Pass the folders to the statscore (with the subfolders option)

**Comment by micz** [comment]
To be released in version 2.2.0.
